import { describe, expect, it } from 'vitest'
import { readCatalogue } from './catalogue.ts'
import type { GrooveSpec } from './types.ts'
import { assignMissingUuids, isCanonicalUuid, mintUuid, uuidFailures } from './uuid.ts'

/**
 * Feature-12, Epic 1, Track A. A groove's uuid is INPUT: minted into
 * catalogue.json once and copied outward from there, never generated by the
 * renderer. These are the four things that has to mean — a uuid is recognisable,
 * it is minted only where it is missing, the committed catalogue carries one per
 * groove, and the build guard can name whichever groove broke the rule.
 */

const A = '9f1c2e40-7b3a-4c15-9d8e-2a6b41f0c7de'
const B = 'c0105415-48cb-43cb-a54d-996fcdb40d94'
const C = '34d62aba-a264-469c-836b-be57fcc69c0b'

function spec(id: string, uuid: string): GrooveSpec {
  return { id, uuid, template: 'straight-funk', seed: Number(id.slice(-2)) }
}

// Step A1 — R1a, AC14.
describe('isCanonicalUuid', () => {
  it('accepts a canonical lowercase hyphenated v4 uuid', () => {
    expect(isCanonicalUuid(A)).toBe(true)
  })

  it('rejects everything that is not one', () => {
    // Empty, a catalogue id, the same uuid uppercased (R1a: lowercase is the
    // canonical form, and the manifest stores the canonical form), a version
    // digit that is not 4, and a truncation one character short.
    expect(isCanonicalUuid('')).toBe(false)
    expect(isCanonicalUuid('groove-01')).toBe(false)
    expect(isCanonicalUuid(A.toUpperCase())).toBe(false)
    expect(isCanonicalUuid('9f1c2e40-7b3a-1c15-9d8e-2a6b41f0c7de')).toBe(false)
    expect(isCanonicalUuid(A.slice(0, 35))).toBe(false)
  })

  it('rejects a value that is not a string at all', () => {
    // The catalogue is JSON, so a hand edit can put anything here — and the
    // guard has to survive being handed it rather than throwing.
    expect(isCanonicalUuid(undefined)).toBe(false)
    expect(isCanonicalUuid(42)).toBe(false)
  })
})

// Step A2 — R1, R4. The mint produces what the recogniser accepts, and the
// type carries the field.
describe('mintUuid', () => {
  it('mints what isCanonicalUuid accepts', () => {
    expect(isCanonicalUuid(mintUuid())).toBe(true)
  })

  it('is a field of GrooveSpec', () => {
    const value: GrooveSpec = { id: 'groove-99', uuid: mintUuid(), template: 't', seed: 1 }
    expect(isCanonicalUuid(value.uuid)).toBe(true)
  })

  it('mints a different value every time', () => {
    expect(mintUuid()).not.toBe(mintUuid())
  })
})

// Step A3 — R2, R6. The backfill is the repair path, so it must be safe to run
// twice: it fills in what is missing and touches nothing else.
describe('assignMissingUuids', () => {
  const specs: GrooveSpec[] = [spec('groove-01', ''), spec('groove-02', A), spec('groove-03', '')]

  function fakeMint(): () => string {
    const values = [B, C]
    let i = 0
    return () => values[i++]
  }

  it('leaves a uuid a groove already holds exactly as it was', () => {
    const out = assignMissingUuids(specs, fakeMint())
    expect(out).toHaveLength(3)
    expect(out[1].uuid).toBe(A)
  })

  it('mints one for each groove that has none', () => {
    const out = assignMissingUuids(specs, fakeMint())
    expect(out[0].uuid).toBe(B)
    expect(out[2].uuid).toBe(C)
  })

  it('changes nothing on a second pass', () => {
    const once = assignMissingUuids(specs, fakeMint())
    const twice = assignMissingUuids(once, () => {
      throw new Error('assignMissingUuids minted again on an already-complete catalogue')
    })
    expect(twice).toEqual(once)
  })

  it('re-mints a uuid that is present but malformed', () => {
    // A hand edit that mangles a uuid is the same repair job as one that drops
    // it: what the catalogue holds is not a uuid either way.
    const [out] = assignMissingUuids([spec('groove-01', 'not-a-uuid')], () => B)
    expect(out.uuid).toBe(B)
  })

  it('writes uuid directly after id, so the catalogue diff is one line per groove', () => {
    const [out] = assignMissingUuids([spec('groove-01', '')], () => B)
    expect(Object.keys(out)).toEqual(['id', 'uuid', 'template', 'seed'])
  })
})

// Step A4 — R5, R6, AC5. The committed file, not a fixture.
describe('the committed catalogue', () => {
  const specs = readCatalogue()

  it('gives every groove a canonical uuid', () => {
    for (const s of specs) {
      expect(isCanonicalUuid(s.uuid), `${s.id} has no canonical uuid: ${String(s.uuid)}`).toBe(true)
    }
  })

  it('gives no two grooves the same uuid', () => {
    expect(new Set(specs.map((s) => s.uuid)).size).toBe(specs.length)
  })

  it('passes the guard it is checked by', () => {
    expect(uuidFailures(specs)).toEqual([])
  })
})

// Step A7 — R3, R8, R9, R10, AC3, AC4. Every failure names the groove.
describe('uuidFailures', () => {
  it('finds nothing wrong with a clean catalogue', () => {
    expect(uuidFailures([spec('groove-01', A), spec('groove-02', B)])).toEqual([])
  })

  it('names the groove whose uuid is absent', () => {
    const failures = uuidFailures([spec('groove-01', A), { id: 'groove-02', template: 'straight-funk', seed: 2 } as GrooveSpec])
    expect(failures).toHaveLength(1)
    expect(failures[0].check).toBe('uuid-missing')
    expect(failures[0].detail).toContain('groove-02')
  })

  it('names both grooves that share a uuid', () => {
    const failures = uuidFailures([
      spec('groove-01', A),
      spec('groove-02', B),
      spec('groove-03', A),
    ])
    expect(failures).toHaveLength(1)
    expect(failures[0].check).toBe('uuid-duplicate')
    expect(failures[0].detail).toContain('groove-01')
    expect(failures[0].detail).toContain('groove-03')
    expect(failures[0].detail).toContain(A)
    // The groove that is not part of the collision is not implicated in it.
    expect(failures[0].detail).not.toContain('groove-02')
  })

  it('names the groove whose uuid is malformed, and the value it holds', () => {
    const failures = uuidFailures([spec('groove-04', 'not-a-uuid')])
    expect(failures).toHaveLength(1)
    expect(failures[0].check).toBe('uuid-malformed')
    expect(failures[0].detail).toContain('groove-04')
    expect(failures[0].detail).toContain('not-a-uuid')
  })

  it('reports every fault in one pass rather than the first one it meets', () => {
    const checks = uuidFailures([
      spec('groove-01', A),
      { id: 'groove-02', template: 'straight-funk', seed: 2 } as GrooveSpec,
      spec('groove-03', A),
      spec('groove-04', 'NOT-A-UUID'),
    ]).map((f) => f.check)
    expect(new Set(checks)).toEqual(new Set(['uuid-missing', 'uuid-duplicate', 'uuid-malformed']))
  })
})
