import type { FeelTemplate } from '../types.ts'

export const brightStraight: FeelTemplate = {
  id: 'bright-straight',
  tempoRange: [116, 132],
  subdivision: 8,
  swing: 0.06,
  flavours: ['lydian', 'ionian'],
  voices: ['kick', 'snare', 'hatClosed', 'hatOpen', 'rim', 'tomHigh', 'tomLow', 'bass', 'comp', 'bongoHigh', 'bongoLow'],
  humanize: {
    timingMs: 6,
    velocity: 0.05,
    lean: { snare: 5, hatClosed: -2, rim: 3 },
    driftDepth: 0.004,
  },
  gain: {
    bongoHigh: -16,
    bongoLow: -15,
    tomHigh: -15,
    tomLow: -14,
    kick: -12,
    snare: -10,
    hatClosed: -11,
    hatOpen: -17,
    rim: -8,
    bass: -3,
    comp: -5,
  },
  pan: {
    bongoHigh: 0.3,
    bongoLow: 0.18,
    tomHigh: 0.24,
    tomLow: -0.28,
    kick: 0,
    snare: 0.08,
    hatClosed: 0.42,
    hatOpen: 0.44,
    rim: -0.36,
    bass: 0,
    comp: 0.3,
  },
  passes: 4,
  density: { minPerBar: 17, maxPerBar: 40 },
}
