import type { FeelTemplate } from '../types.ts'

export const straightFunk: FeelTemplate = {
  id: 'straight-funk',
  tempoRange: [94, 106],
  subdivision: 16,
  swing: 0.18,
  flavours: ['dorian', 'mixolydian'],
  voices: ['kick', 'snare', 'hatClosed', 'hatOpen', 'rim', 'tomHigh', 'tomLow', 'bass', 'comp'],
  humanize: {
    timingMs: 9,
    velocity: 0.09,
    lean: { snare: 9, hatClosed: -3, hatOpen: -3, rim: 4 },
    driftDepth: 0.005,
  },
  gain: {
    tomHigh: -13,
    tomLow: -12,
    kick: -8,
    snare: -8,
    hatClosed: -9,
    hatOpen: -16,
    rim: -11,
    bass: -1,
    comp: -3,
  },
  pan: {
    tomHigh: 0.22,
    tomLow: -0.26,
    kick: 0,
    snare: -0.05,
    hatClosed: 0.35,
    hatOpen: 0.4,
    rim: -0.3,
    bass: 0,
    comp: -0.2,
  },
  passes: 4,
  density: { minPerBar: 18, maxPerBar: 44 },
}
